language: node_js

notifications:
    email:
        - yiminghe@gmail.com

node_js:
  - 6

script:
  - npm test
  - npm run cover
  - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls
